apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway-pdb
  namespace: velyxora
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: api-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: wallet-service-pdb
  namespace: velyxora
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: wallet-service
