apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service
  namespace: velyxora
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      containers:
      - name: wallet-service
        image: velyxora/wallet-service:latest
        env:
        - name: DB_HOST
          value: "postgres"
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        resources:
          limits:
            cpu: "1"
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 512Mi
